services:
  app:
    container_name: contentflow-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=https://hamza.whatsgrow.io
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
    ports:
      - "3001:3001"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    domains:
      - domain: ham.whatsgrow.io
        port: 3001
